name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: run .travis.yml
      # You may pin to the exact commit or the version.
      # uses: ktomk/run-travis-yml@fab26d29082e009f43121c9e922be2555fa0a5cb
      uses: ktomk/run-travis-yml@v1.7.0
      with:
      # Path to `.travis.yml` file. Leave empty / unset for default
      # `.travis.yml`. Relative to project root. Overrides the
      # `TRAVIS_YAML_FILE` environment variable if non-empty.

      file: # optional, default is 
      # Space separated list of steps to run. Leave empty
      # / unset to run all custom steps.

      steps: # default is 
      # Deprecated: Space separated list of steps to run
      # (originally misnamed stages). Leave empty / unset to run
      # all custom steps. Use `inputs.steps` instead. Note:
      # `input.stages` might be re-used for different or just error
      # in a future version; change early.

      stages: # default is 
      # Allow the .travis.yml build to fail. Possible values are
      # `true` and `false`. Overrides the `TRAVIS_ALLOW_FAILURE`
      # environment variable if set.

      allow-failure: # optional, default is 
      # alias of `allow-failure`
      allow_failure: # optional, default is 
      # Name of the run-job. Possible values are the ones the
      # plan is listing. By default, the original root step-scripts
      # are in use. If a job has a name, it can be used as well.

      run-job: # optional, default is 
      # alias of `run-job`
      run_job: # optional, default is 
      # Dry-run the run-job. Possible values are `true` and
      # `false`.

      dry-run-job: # optional, default is 
      # alias of `dry-run-job`
      dry_run_job: # optional, default is 
