name: university-db

on: [push, pull_request, workflow_dispatch]

jobs:
  university-db:
    runs-on: ubuntu-latest
    env:
      path: build
    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V

  formatting_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check
      uses: actions/checkout@main
      with:
        check_path: 'repository'
